name: aandi_oj_api
description: OJ APIs package for AANDI admin service
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  aandi_api_endpoints:
    path: ../aandi_api_endpoints
  aandi_api_protocol:
    git:
      url: https://github.com/Team-AnI/A-AND-I-PROTOCOL-API.git
      ref: v0.1.0
  aandi_auth:
    path: ../auth_api
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  dio: ^5.9.2

dev_dependencies:
  lints: ^6.0.0
  build_runner: ^2.4.13
  freezed: ^3.0.6
  json_serializable: ^6.9.0
  test: any
